# Generated by Django 3.1 on 2020-08-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishe_date',
            new_name='published_date',
        ),
    ]
