# Generated by Django 3.1 on 2020-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField()),
                ('endTime', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=50)),
                ('desc', models.TextField(default='')),
            ],
        ),
    ]
